development:
  database_url: postgresql://brandon:<db_password>@127.0.0.1:5432/avengers

staging:
  database_url: postgresql://brandon:<db_password>@db:5432/avengers

production:
  database_url: postgresql://<username>:<db_password>@some-awesome-domain.com:5432/avengers
