version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - 5432:5432
    volumes:
      - /dev/avengers_api/db:/var/lib/postgresql/data

  api:
    build: ./lib
    environment:
      GIT_COMMIT: $GIT_COMMIT
    ports:
      - "80:8080"
    volumes:
      - /dev/avengers_api/logs:/usr/src/app/logs
